export const airlines = [
  // --- Indian Carriers (International) ---
  'Air India',
  'Air India Express',
  'Akasa Air',
  'IndiGo-Airlines',
  'SpiceJet',
  // --- Major Foreign Carriers ---
  'Aegean Airlines',
  'Aeroflot',
  'Air Arabia',
  'Air Canada',
  'Air France',
  'Air Mauritius',
  'All Nippon Airways',
  'American Airlines',
  'Biman Bangladesh Airlines',
  'British Airways',
  'Cathay Pacific',
  'Delta Air Lines',
  'Druk Air',
  'EgyptAir',
  'Emirates',
  'Ethiopian Airlines',
  'Etihad Airways',
  'Finnair',
  'flydubai',
  'Gulf Air',
  'Japan Airlines',
  'Jazeera Airways',
  'Kenya Airways',
  'KLM',
  'Korean Air',
  'Kuwait Airways',
  'LOT Polish Airlines',
  'Lufthansa',
  'Malaysia Airlines',
  'Maldivian',
  'Oman Air',
  'Qantas',
  'Qatar Airways',
  'Saudia',
  'Singapore Airlines',
  'SriLankan Airlines',
  'Swiss International Air Lines',
  'Thai Airways',
  'Turkish Airlines',
  'United Airlines',
  'Uzbekistan Airways',
  'VietJet Air',
  'Vietnam Airlines',
  'Virgin Atlantic'
];
export const cities = [
  // --- Major Indian International Gateways ---
  'Ahmedabad',
  'Amritsar',
  'Bangalore',
  'Chennai',
  'Cochin',
  'Coimbatore',
  'Delhi',
  'Goa',
  'Guwahati',
  'Hyderabad',
  'Jaipur',
  'Kolkata',
  'Kozhikode',
  'Lucknow',
  'Mumbai',
  'Nagpur',
  'Pune',
  'Thiruvananthapuram',
  'Tiruchirappalli',
  'Varanasi',

  // --- Major International Destinations ---
  'Abu Dhabi',
  'Almaty',
  'Amsterdam',
  'Athens',
  'Baku',
  'Bangkok',
  'Chicago',
  'Colombo',
  'Copenhagen',
  'Dammam',
  'Denpasar (Bali)',
  'Dhaka',
  'Doha',
  'Dubai',
  'Frankfurt',
  'Guangzhou',
  'Hanoi',
  'Ho Chi Minh City',
  'Hong Kong',
  'Istanbul',
  'Jeddah',
  'Kathmandu',
  'Kuala Lumpur',
  'Kuwait City',
  'London',
  'Malé',
  'Manila',
  'Melbourne',
  'Milan',
  'Moscow',
  'Munich',
  'Muscat',
  'Nairobi',
  'New York',
  'Newark',
  'Paris',
  'Phuket',
  'Riyadh',
  'Rome',
  'San Francisco',
  'Seoul',
  'Shanghai',
  'Singapore',
  'Sydney',
  'Tashkent',
  'Tbilisi',
  'Tokyo',
  'Toronto',
  'Vancouver',
  'Vienna',
  'Warsaw',
  'Zurich'
];

export const navLinks = [
  { name: 'Flight Status', href: '#' },
  { name: 'Airlines', href: '#' },
  { name: 'Airports', href: '#' },
  { name: 'My Trips', href: '#' }
];

export const footerLinks = {
  services: [
    { name: 'Flight Status', href: '#' },
    { name: 'Airport Information', href: '#' },
    { name: 'Airline Partners', href: '#' }
  ],
  flightTracker: [
    { name: 'About Us', href: '#' },
    { name: 'Contact Us', href: '#' },
    { name: 'Careers', href: '#' }
  ],
  quickLinks: [
    { name: 'Customer Support', href: '#' },
    { name: 'Terms & Conditions', href: '#' },
    { name: 'Privacy Policy', href: '#' }
  ],
  resources: [
    { name: 'Flight Delay Compensation', href: '#' },
    { name: 'Travel Tips', href: '#' },
    { name: 'FAQ', href: '#' }
  ]
};